services:
  db:
    image: postgres:16.1
    container_name: filmorate-db
    ports:
      - "6541:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/filmorate/data/
    environment:
      - POSTGRES_DB=filmorate
      - POSTGRES_USER=filmorate
      - POSTGRES_PASSWORD=filmorate
      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10